# Generated by Django 3.0.8 on 2020-08-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectToWifi',
            new_name='Wifi',
        ),
    ]
